version: '3.8'

volumes:
  postgres:
    driver: local

services:
  database:
    image: postgres:latest
    shm_size: '4gb'
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: investtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432